import { createStitches } from '@stitches/react';
import type * as Stitches from '@stitches/react';
import {
  blackA,
  mauveDark,
  mauveDarkA,
  tealDark,
  tealDarkA,
  violetDark,
  violetDarkA,
  redDark,
  slateDark,
} from '@radix-ui/colors';

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      ...blackA,
      ...mauveDark,
      ...mauveDarkA,
      ...tealDark,
      ...tealDarkA,
      ...violetDark,
      ...violetDarkA,
      ...redDark,
      ...slateDark,
      subtleText: '$mauve11',
      text: '$mauve12',
    },
    fontSizes: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
      '7xl': '4.5rem',
      '8xl': '6rem',
      '9xl': '8rem',
    },
    fontWeights: {
      regular: 'normal',
      medium: 500,
      bold: 'bold',
    },
    lineHeights: {
      xs: '1rem',
      sm: '1.25rem',
      base: '1.5rem',
      lg: '1.75rem',
      xl: '1.75rem',
      '2xl': '2rem',
      '3xl': '2.25rem',
      '4xl': '2.5rem',
      '5xl': '1',
      '6xl': '1',
      '7xl': '1',
      '8xl': '1',
      '9xl': '1',
      none: 1,
      tight: 1.25,
      snug: 1.375,
      normal: 1.5,
      relaxed: 1.625,
      loose: 2,
    },
    space: {
      px: '1px',
      1: '0.25rem',
      '1.5': '0.375rem',
      2: '0.5rem',
      '2.5': '0.625rem',
      3: '0.75rem',
      '3.5': '0.875rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
      12: '3rem',
      14: '3.5rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
      28: '7rem',
      32: '8rem',
      36: '9rem',
      40: '10rem',
      44: '11rem',
      48: '12rem',
      52: '13rem',
      56: '14rem',
      60: '15rem',
      64: '16rem',
      72: '18rem',
      80: '20rem',
      96: '24rem',
    },
    sizes: {
      px: '1px',
      '0.5': '0.125rem',
      1: '0.25rem',
      '1.5': '0.375rem',
      2: '0.5rem',
      '2.5': '0.625rem',
      3: '0.75rem',
      '3.5': '0.875rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
      12: '3rem',
      14: '3.5rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
      28: '7rem',
      32: '8rem',
      36: '9rem',
      40: '10rem',
      44: '11rem',
      48: '12rem',
      52: '13rem',
      56: '14rem',
      60: '15rem',
      64: '16rem',
      72: '18rem',
      80: '20rem',
      96: '24rem',
      full: '100%',
      '1/2': '50%',
    },
    radii: {
      none: '0px',
      sm: '0.125rem',
      md: '0.375rem',
      lg: '0.5rem',
      round: '9999px',
    },
    fonts: {
      $sans: 'Walheim, sans-serif',
    },
    shadows: {
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    },
  },
  utils: {
    marginX: (value: Stitches.ScaleValue<'space'>) => ({
      marginLeft: value,
      marginRight: value,
    }),
    marginY: (value: Stitches.ScaleValue<'space'>) => ({
      marginTop: value,
      marginBottom: value,
    }),
    paddingX: (value: Stitches.ScaleValue<'space'>) => ({
      paddingLeft: value,
      paddingRight: value,
    }),
    paddingY: (value: Stitches.ScaleValue<'space'>) => ({
      paddingTop: value,
      paddingBottom: value,
    }),
    insetX: (value: Stitches.ScaleValue<'space'>) => ({
      left: value,
      right: value,
    }),
    cols: (num: number) => ({
      gridTemplateColumns: `repeat(${num}, minmax(0, 1fr))`,
    }),
    colStart: (col: number) => ({
      gridColumnStart: col,
    }),
    colSpan: (cols: number) => ({
      gridColumn: `span ${cols} / span ${cols}`,
    }),
    textSize: (size: Stitches.ScaleValue<'fontSizes'>) => ({
      fontSize: size,
      lineHeight: size,
    }),
  },
  media: {
    xl: '(max-width:1536px)',
    lg: '(max-width:1280px)',
    md: '(max-width:1024px)',
  },
});

export type CSS = Stitches.CSS<typeof config>;
export type PropertyValue<T extends keyof Stitches.CSSProperties> =
  Stitches.PropertyValue<T, typeof config>;
